### ISSUE TITLE
IllegalStateException: [GET http://www.threecopies.com/] failed in 26ms: javax.xml.transform.TransformerConfigurationExc...

### ISSUE THREAD

**Issue by yegor256** [yegor256/threecopies#2]
https://sentry.io/zerocracy/threecopies/issues/343297530/

```
FileNotFoundException: /xsl/index.xsl (No such file or directory)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
...
(44 additional frame(s) were not displayed)

TransformerConfigurationException: /xsl/index.xsl (No such file or directory)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:1018)
    at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:791)
    at org.takes.rs.RsXslt.transformer(RsXslt.java:228)
    at org.takes.rs.RsXslt.transform(RsXslt.java:160)
    at org.takes.rs.RsXslt.transform(RsXslt.java:131)
...
(29 additional frame(s) were not displayed)

IOException: javax.xml.transform.TransformerConfigurationException: /xsl/index.xsl (No such file or directory)
    at org.takes.rs.RsXslt.transform(RsXslt.java:133)
    at org.takes.rs.RsXslt.access$100(RsXslt.java:89)
    at org.takes.rs.RsXslt$1.body(RsXslt.java:113)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
    at org.takes.facets.fork.RsFork$1.body(RsFork.java:74)
...
(25 additional frame(s) were not displayed)

IllegalStateException: [GET http://www.threecopies.com/] failed in 26ms: javax.xml.transform.TransformerConfigurationException: /xsl/index.xsl (No such file or directory)
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.access$100(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$2.body(TkFallback.java:199)
    at org.takes.rs.RsWithHeader$1.body(RsWithHeader.java:114)
    at org.takes.rs.RsWrap.body(RsWrap.java:65)
...
(16 additional frame(s) were not displayed)

[GET http://www.threecopies.com/] failed in 26ms: javax.xml.transform.TransformerConfigurationException: /xsl/index.xsl (No such file or directory)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.1.1`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/threecopies#2` was not in scope
